<?php

$excel_students = [
    ['reg_no' => '200', 'last_name' => 'كنان', 'first_name' => 'لينة', 'father_name' => 'رابح', 'class' => 'الرابعة ا 1', 'birth_date' => '2016-07-05', 'birth_place' => 'القبة', 'address' => 'براقي/ محمد قدور'],
    ['reg_no' => '201', 'last_name' => 'ديلمي', 'first_name' => 'محمد إسلام', 'father_name' => 'محمد شكير', 'class' => 'الرابعة ا 1', 'birth_date' => '2016-12-03', 'birth_place' => 'عين طاية', 'address' => 'الكاليتوس/ خليفاتي علي ش5 ر15'],
    ['reg_no' => '202', 'last_name' => 'عبان', 'first_name' => 'أحمد', 'father_name' => 'فاتح', 'class' => 'الرابعة ا 1', 'birth_date' => '2016-08-22', 'birth_place' => 'بوروبة', 'address' => 'براقي / بن غازي'],
    ['reg_no' => '203', 'last_name' => 'ياسر', 'first_name' => 'سهيل', 'father_name' => 'رشيد', 'class' => 'الرابعة ا 1', 'birth_date' => '2016-05-22', 'birth_place' => 'القبة', 'address' => 'براقي / ق ر77 ش م جعدي'],
    ['reg_no' => '204', 'last_name' => 'رحيم', 'first_name' => 'محمد أنس', 'father_name' => 'نبيل', 'class' => 'الرابعة ا 1', 'birth_date' => '2017-02-06', 'birth_place' => 'بئر مراد رايس', 'address' => 'الدهيمات/ ... R'],
    ['reg_no' => '205', 'last_name' => 'بورنان', 'first_name' => 'نذير', 'father_name' => 'محمد', 'class' => 'الرابعة ا 1', 'birth_date' => '2016-04-21', 'birth_place' => 'حسين داي', 'address' => 'براقي / حي المرجة3'],
    ['reg_no' => '206', 'last_name' => 'سيلم', 'first_name' => 'دحمان', 'father_name' => 'عبد القادر', 'class' => 'الرابعة ا 1', 'birth_date' => '2016-09-01', 'birth_place' => 'بئر مراد رايس', 'address' => 'براقي/ بن طلحة'],
    ['reg_no' => '207', 'last_name' => 'عمراوي', 'first_name' => 'مارية', 'father_name' => 'طارق', 'class' => 'الرابعة ا 1', 'birth_date' => '2016-04-18', 'birth_place' => 'حسين داي', 'address' => 'بوروبة/ إقامة نقاش'],
    ['reg_no' => '208', 'last_name' => 'بوسويسي', 'first_name' => 'سارة', 'father_name' => 'عز الدين', 'class' => 'الرابعة ا 1', 'birth_date' => '2016-04-19', 'birth_place' => 'برج الكيفان', 'address' => 'الأربعاء/ بن دالي علي R'],
    ['reg_no' => '209', 'last_name' => 'كولال', 'first_name' => 'ميرا', 'father_name' => 'خليف سارة', 'class' => 'الرابعة ا 1', 'birth_date' => '2016-09-01', 'birth_place' => 'بئر خادم', 'address' => 'سيدي موسى/ EPLF'],
    ['reg_no' => '210', 'last_name' => 'قلي', 'first_name' => 'آدم', 'father_name' => 'محمد', 'class' => 'الرابعة ا 1', 'birth_date' => '2016-07-08', 'birth_place' => 'القبة', 'address' => 'براقي / حي 360 م ع B'],
    ['reg_no' => '211', 'last_name' => 'عمروش', 'first_name' => 'ندى', 'father_name' => 'خالد', 'class' => 'الرابعة ا 1', 'birth_date' => '2017-02-22', 'birth_place' => 'بوروبة', 'address' => 'براقي / بن طلحة'],
    ['reg_no' => '212', 'last_name' => 'رحمون', 'first_name' => 'تيسير منى', 'father_name' => 'محمد', 'class' => 'الرابعة ا 1', 'birth_date' => '2016-05-24', 'birth_place' => 'ولاد فايت', 'address' => 'براقي / طويلب المرجة'],
    ['reg_no' => '213', 'last_name' => 'مكيد', 'first_name' => 'دعاء', 'father_name' => 'رمضان', 'class' => 'الرابعة ا 1', 'birth_date' => '2016-09-18', 'birth_place' => 'تابلاط', 'address' => 'خ/ أولاد سلامة'],
    ['reg_no' => '214', 'last_name' => 'قاسي', 'first_name' => 'نهال', 'father_name' => 'قدور', 'class' => 'الرابعة ا 1', 'birth_date' => '2016-10-29', 'birth_place' => 'الجزائر', 'address' => 'خ/ ...'],
    ['reg_no' => '215', 'last_name' => 'خروب', 'first_name' => 'مهدي محمد', 'father_name' => 'نبيل', 'class' => 'الرابعة ا 1', 'birth_date' => '2016-04-20', 'birth_place' => 'بئر مراد رايس', 'address' => 'خ/ بوقرة/ اولاد سلامة المركزية'],
    ['reg_no' => '216', 'last_name' => 'بليدي', 'first_name' => 'عبد الوهاب', 'father_name' => 'محمد', 'class' => 'الرابعة ا 1', 'birth_date' => '2016-10-16', 'birth_place' => 'بئر خادم', 'address' => 'خ/ عين النعجة / جسر ق'],
    ['reg_no' => '217', 'last_name' => 'شريف', 'first_name' => 'أحمد الصديق', 'father_name' => 'بدر الدين', 'class' => 'الرابعة ا 2', 'birth_date' => '2017-02-15', 'birth_place' => 'القبة', 'address' => 'براقي / بن غازي'],
    ['reg_no' => '218', 'last_name' => 'رعاب', 'first_name' => 'عائشة', 'father_name' => 'هشام', 'class' => 'الرابعة ا 2', 'birth_date' => '2016-07-15', 'birth_place' => 'بئر خادم', 'address' => 'خ/ باباعلي'],
    ['reg_no' => '219', 'last_name' => 'فراش', 'first_name' => 'لوجين', 'father_name' => 'يوسف', 'class' => 'الرابعة ا 2', 'birth_date' => '2016-11-05', 'birth_place' => 'بئر خادم', 'address' => 'بوقرة/ طريق الاربعاء'],
    ['reg_no' => '220', 'last_name' => 'قارة', 'first_name' => 'رسيم', 'father_name' => 'محمد لمين', 'class' => 'الرابعة ا 2', 'birth_date' => '2016-11-15', 'birth_place' => 'زرالدة', 'address' => 'براقي / بن غازي'],
    ['reg_no' => '221', 'last_name' => 'لكحل', 'first_name' => 'آدم', 'father_name' => 'عبد الله', 'class' => 'الرابعة ا 2', 'birth_date' => '2017-01-02', 'birth_place' => 'سيدي امحمد', 'address' => 'براقي/ قسم 118'],
    ['reg_no' => '222', 'last_name' => 'غلال', 'first_name' => 'الاء', 'father_name' => 'بلال', 'class' => 'الرابعة ا 2', 'birth_date' => '2016-04-04', 'birth_place' => 'القبة', 'address' => 'براقي / بن غازي'],
    ['reg_no' => '223', 'last_name' => 'نوفل', 'first_name' => 'رامي', 'father_name' => 'عبد الرحيم', 'class' => 'الرابعة ا 2', 'birth_date' => '2016-05-17', 'birth_place' => 'الحراش', 'address' => 'خ/ كركوش ر250 اولاد سلامة'],
    ['reg_no' => '224', 'last_name' => 'موطاسي', 'first_name' => 'وائل', 'father_name' => 'عبد القادر', 'class' => 'الرابعة ا 2', 'birth_date' => '2016-09-17', 'birth_place' => 'بئر خادم', 'address' => 'الكاليتوس/ القصر الأحمر'],
    ['reg_no' => '225', 'last_name' => 'إبراهيم', 'first_name' => 'نورهان كوثر', 'father_name' => 'جلول', 'class' => 'الرابعة ا 2', 'birth_date' => '2016-05-31', 'birth_place' => 'حسين داي', 'address' => 'خ/ الكاليتوس ح الكبير 73'],
    ['reg_no' => '226', 'last_name' => 'بونهاك', 'first_name' => 'عبد الله', 'father_name' => 'الشريف', 'class' => 'الرابعة ا 2', 'birth_date' => '2016-06-23', 'birth_place' => 'الرويبة', 'address' => 'سيدي موسى/ اولاد علال'],
    ['reg_no' => '227', 'last_name' => 'عيش', 'first_name' => 'محمد', 'father_name' => 'منير', 'class' => 'الرابعة ا 2', 'birth_date' => '2016-05-23', 'birth_place' => 'برج الكيفان', 'address' => 'خ/ براقي القسم'],
    ['reg_no' => '228', 'last_name' => 'بلفوضيل', 'first_name' => 'علي', 'father_name' => 'محمد', 'class' => 'الرابعة ا 2', 'birth_date' => '2016-08-16', 'birth_place' => 'بئر خادم', 'address' => 'بوقرة/ قطعة 138'],
    ['reg_no' => '229', 'last_name' => 'رباعي', 'first_name' => 'مالك', 'father_name' => 'محمد', 'class' => 'الرابعة ا 2', 'birth_date' => '2016-06-09', 'birth_place' => 'برج الكيفان', 'address' => 'الأربعاء/حي 300 م'],
    ['reg_no' => '230', 'last_name' => 'بوسعيد', 'first_name' => 'عبد الودود', 'father_name' => 'وليد', 'class' => 'الرابعة ا 2', 'birth_date' => '2016-07-25', 'birth_place' => 'حيدرة', 'address' => 'براقي / بن غازي'],
    ['reg_no' => '231', 'last_name' => 'دريهم', 'first_name' => 'ألاء', 'father_name' => 'سيد علي', 'class' => 'الرابعة ا 2', 'birth_date' => '2016-10-15', 'birth_place' => 'حراش', 'address' => 'الأربعاء/ المازونية'],
    ['reg_no' => '74', 'last_name' => 'كتو', 'first_name' => 'طارق', 'father_name' => 'فاروق', 'class' => 'الثانية م 1', 'birth_date' => '2013-07-16', 'birth_place' => 'برج الكيفان', 'address' => 'براقي / ...'],
    ['reg_no' => '75', 'last_name' => 'زمري', 'first_name' => 'عبد الباسط', 'father_name' => 'مصطفى', 'class' => 'الثانية م 1', 'birth_date' => '2012-01-14', 'birth_place' => 'حسين داي', 'address' => 'براقي'],
    ['reg_no' => '76', 'last_name' => 'جبار', 'first_name' => 'أيوب', 'father_name' => 'علي', 'class' => 'الثانية م 1', 'birth_date' => '2013-10-08', 'birth_place' => 'بئر مراد رايس', 'address' => 'القبة / بن عمر'],
    ['reg_no' => '77', 'last_name' => 'تواتي', 'first_name' => 'سفيان', 'father_name' => 'محمد', 'class' => 'الثانية م 1', 'birth_date' => '2012-06-13', 'birth_place' => 'عين طاية', 'address' => 'براقي / حي المرجة3'],
    ['reg_no' => '78', 'last_name' => 'عون', 'first_name' => 'صلاح الدين', 'father_name' => 'طارق', 'class' => 'الثانية م 1', 'birth_date' => '2013-05-05', 'birth_place' => 'حسين داي', 'address' => 'بوروبة/ إقامة نقاش'],
    ['reg_no' => '79', 'last_name' => 'قدور', 'first_name' => 'محمد عصام', 'father_name' => 'مولود', 'class' => 'الثانية م 1', 'birth_date' => '2014-01-23', 'birth_place' => 'زرالدة', 'address' => 'خ/ بن طلحة الحامة 2'],
    ['reg_no' => '80', 'last_name' => 'شيرابي', 'first_name' => 'عبد الصمد', 'father_name' => 'محمد', 'class' => 'الثانية م 1', 'birth_date' => '2012-12-31', 'birth_place' => 'القبة', 'address' => 'براقي / مسجد البشير'],
    ['reg_no' => '81', 'last_name' => 'زويش', 'first_name' => 'هشام', 'father_name' => 'رشيد', 'class' => 'الثانية م 1', 'birth_date' => '2013-05-23', 'birth_place' => 'بئر خادم', 'address' => 'براقي / حي محمودي محمد'],
    ['reg_no' => '82', 'last_name' => 'عماري', 'first_name' => 'يونس', 'father_name' => 'صحراوي', 'class' => 'الثانية م 1', 'birth_date' => '2013-06-06', 'birth_place' => 'براقي', 'address' => 'خ/ ...'],
    ['reg_no' => '83', 'last_name' => 'قبال', 'first_name' => 'هيثم', 'father_name' => 'مراد', 'class' => 'الثانية م 1', 'birth_date' => '2013-03-04', 'birth_place' => 'بئر مراد رايس', 'address' => 'براقي / دربوز'],
    ['reg_no' => '84', 'last_name' => 'لزريف', 'first_name' => 'حسام', 'father_name' => 'العيد', 'class' => 'الثانية م 1', 'birth_date' => '2013-10-03', 'birth_place' => 'جسر قسنطينة', 'address' => 'خ/ سيدي موسى'],
    ['reg_no' => '85', 'last_name' => 'صياد', 'first_name' => 'عبد الله', 'father_name' => 'رشيد', 'class' => 'الثانية م 1', 'birth_date' => '2013-10-12', 'birth_place' => 'حسين داي', 'address' => 'بوقرة/ العبازيز'],
    ['reg_no' => '86', 'last_name' => 'بن ناصر', 'first_name' => 'عاصم', 'father_name' => 'ابراهيم', 'class' => 'الثانية م 1', 'birth_date' => '2013-03-25', 'birth_place' => 'القبة', 'address' => 'براقي / ح ميهوب'],
    ['reg_no' => '87', 'last_name' => 'دودو', 'first_name' => 'كريم', 'father_name' => 'محي الدين', 'class' => 'الثانية م 1', 'birth_date' => '2013-07-10', 'birth_place' => 'حسين داي', 'address' => 'الكاليتوس/ حي راشيد سعد الله'],
    ['reg_no' => '88', 'last_name' => 'باباوعمر', 'first_name' => 'وائل', 'father_name' => 'محمد الأمين', 'class' => 'الثانية م 1', 'birth_date' => '2014-02-26', 'birth_place' => 'بئر مراد رايس', 'address' => 'الأربعاء/20 أوت'],
    ['reg_no' => '89', 'last_name' => 'الكشبور', 'first_name' => 'شمس الدين/وائل', 'father_name' => 'قاسي كريم', 'class' => 'الثانية م 1', 'birth_date' => '2013-08-03', 'birth_place' => 'الأربعاء', 'address' => 'خ/ براقي حي 2004'],
    ['reg_no' => '90', 'last_name' => 'دريهم', 'first_name' => 'يونس عبد الرحمن', 'father_name' => 'يزيد', 'class' => 'الثانية م 2', 'birth_date' => '2012-12-04', 'birth_place' => 'القبة', 'address' => 'براقي / لعميرات حي بن أيوب'],
    ['reg_no' => '91', 'last_name' => 'مصار', 'first_name' => 'فوزي', 'father_name' => 'محمد', 'class' => 'الثانية م 2', 'birth_date' => '2013-06-10', 'birth_place' => 'الحمامات', 'address' => 'براقي / بن طلحة'],
    ['reg_no' => '92', 'last_name' => 'بوالباني', 'first_name' => 'محمد قصي', 'father_name' => 'يوسف', 'class' => 'الثانية م 2', 'birth_date' => '2013-08-11', 'birth_place' => 'المرادية', 'address' => 'بوقرة/ طريق الاربعاء'],
    ['reg_no' => '93', 'last_name' => 'حمزة', 'first_name' => 'إبراهيم', 'father_name' => 'داود', 'class' => 'الثانية م 2', 'birth_date' => '2013-05-21', 'birth_place' => 'الحراش', 'address' => 'براقي / ...'],
    ['reg_no' => '94', 'last_name' => 'خميس', 'first_name' => 'محمد أمير', 'father_name' => 'عمر', 'class' => 'الثانية م 2', 'birth_date' => '2014-04-03', 'birth_place' => 'حسين داي', 'address' => 'الأربعاء/حي حمزة محمد'],
    ['reg_no' => '95', 'last_name' => 'بومدين', 'first_name' => 'أسامة عبد الوهاب', 'father_name' => 'احمد', 'class' => 'الثانية م 2', 'birth_date' => '2013-08-21', 'birth_place' => 'سمار', 'address' => 'براقي/ مرحبا'],
    ['reg_no' => '96', 'last_name' => 'غربي', 'first_name' => 'محسن', 'father_name' => 'أحمد', 'class' => 'الثانية م 2', 'birth_date' => '2013-07-28', 'birth_place' => 'القبة', 'address' => 'الأربعاء/ بن دالي علي'],
    ['reg_no' => '97', 'last_name' => 'كريبط', 'first_name' => 'جواد', 'father_name' => 'ياسين', 'class' => 'الثانية م 2', 'birth_date' => '2014-01-18', 'birth_place' => 'بولوغين', 'address' => 'الخرايسية / أولاد منديل'],
    ['reg_no' => '98', 'last_name' => 'يعقوبي', 'first_name' => 'محمد', 'father_name' => 'خير الدين', 'class' => 'الثانية م 2', 'birth_date' => '2013-03-01', 'birth_place' => 'أولا فايت', 'address' => 'خ/ الكاليتوس طريق مفتاح'],
    ['reg_no' => '99', 'last_name' => 'الحاج موسى', 'first_name' => 'محمد الصديق', 'father_name' => 'حميد', 'class' => 'الثانية م 2', 'birth_date' => '2013-09-17', 'birth_place' => 'الشفة', 'address' => 'سيدي موسى/ ...'],
    ['reg_no' => '100', 'last_name' => 'شلاح', 'first_name' => 'عبد الله', 'father_name' => 'عبد الحليم', 'class' => 'الثانية م 2', 'birth_date' => '2013-09-24', 'birth_place' => 'القبة', 'address' => 'الكاليتوس/ ...'],
    ['reg_no' => '101', 'last_name' => 'سعيد', 'first_name' => 'يوسف', 'father_name' => 'محمد ', 'class' => 'الثانية م 2', 'birth_date' => '2014-03-09', 'birth_place' => 'براقي', 'address' => 'باباحسن 11ديسمبر ر28'],
    ['reg_no' => '102', 'last_name' => 'حمي', 'first_name' => 'مهدي', 'father_name' => 'رضا', 'class' => 'الثانية م 2', 'birth_date' => '2013-04-30', 'birth_place' => 'بئر خادم', 'address' => 'خ/ ...'],
    ['reg_no' => '103', 'last_name' => 'نجار', 'first_name' => 'عبد الله', 'father_name' => 'محمد', 'class' => 'الثانية م 2', 'birth_date' => '2014-01-12', 'birth_place' => 'بئر مراد رايس', 'address' => 'براقي / قسم 228 '],
    ['reg_no' => '104', 'last_name' => 'هواري', 'first_name' => 'عبد المجيد', 'father_name' => 'بوجمعة', 'class' => 'الثانية م 2', 'birth_date' => '2013-09-18', 'birth_place' => 'الحراش', 'address' => 'سيدي موسى/ ح 318م R'],
    ['reg_no' => '105', 'last_name' => 'مرزوقي', 'first_name' => 'وسيم', 'father_name' => 'مرزاق', 'class' => 'الثانية م 2', 'birth_date' => '2013-05-23', 'birth_place' => 'بئر مراد رايس', 'address' => 'براقي / حي اليرموك'],
];

$excel_teachers = [
    ['full_name' => 'عماري رزيقة', 'subject' => 'اللغة العربية'],
    ['full_name' => 'زياني سمية', 'subject' => 'التاريخ والجغرافيا'],
    ['full_name' => 'عماري رزيقة', 'subject' => 'التربية الإسلامية'],
    ['full_name' => 'زروقي يحي', 'subject' => 'التربية الإسلامية'],
    ['full_name' => 'عماري رزيقة', 'subject' => 'التاريخ و الجغرافيا'],
    ['full_name' => 'عمروش صليحة', 'subject' => 'التربية التشكيلية'],
    ['full_name' => 'عماري رزيقة', 'subject' => 'التربية المدنية'],
    ['full_name' => 'زياني سمية', 'subject' => 'التربية والمدنية'],
    ['full_name' => 'قعلول خديجة', 'subject' => 'اللغة الإنجليزية'],
    ['full_name' => 'سعيداني سمية', 'subject' => 'الرياضيات'],
    ['full_name' => 'عيسو صونيا', 'subject' => 'اللغة الفرنسية'],
    ['full_name' => 'روان يوسف', 'subject' => 'اللغة الإنجليزية'],
    ['full_name' => 'عماري رزيقة', 'subject' => 'ت العلمية والتكنولوجيا'],
    ['full_name' => 'طويلب أمينة', 'subject' => 'اللغة العربية'],
    ['full_name' => 'عماري رزيقة', 'subject' => 'الرياضيات'],
    ['full_name' => 'خاير ليلى', 'subject' => 'اللغة الفرنسية'],
    ['full_name' => 'رماني نادية', 'subject' => 'التربية التشكيلية'],
    ['full_name' => 'بن يحي مراد', 'subject' => 'المعلوماتية'],
    ['full_name' => 'عماري رزيقة', 'subject' => 'التربية الموسيقية'],
    ['full_name' => 'بومدين ياسين', 'subject' => 'ت البدنية والرياضة'],
    ['full_name' => 'بوحدوف حمزة', 'subject' => 'ت البدنية والرياضة'],
    ['full_name' => 'بوخضرة نور ', 'subject' => 'ع الطبيعة والحياة'],
    ['full_name' => 'رضا أمينة', 'subject' => 'ع الفيزيائية والتكنولوجيا'],
];
